apiVersion: v1
kind: Service
metadata:
  name: consul
spec:
  ports:
  - port: 8500
    protocol: TCP
    targetPort: 8500
  selector:
    app: consul
    release: consul
    component: server
  type: LoadBalancer