apiVersion: terraform.patoarvizu.dev/v1
kind: TerraformState
metadata:
  name: password
spec:
  type: consul
  consulConfig:
    path: password
    address: consul:8500
    scheme: http
  target:
    type: secret
    name: password